import { Text, View, Pressable } from 'react-native'

import { HomeStyles } from '../styles/HomeStyles' 

export const HomeScreen = ({navigation}) => {

    return (
    <View style={HomeStyles().container}>
      <Text style={HomeStyles().welcome}>Welcome to random jokes generator!</Text>
      <Text style={HomeStyles().instructionTitle}>Simple usage instruction:</Text>
      <View style={HomeStyles().instructionContainer}>
            <Text style={HomeStyles().text}>1) Press the button to see a list of jokes</Text>
            <Text style={HomeStyles().text}>2) Press and hold the joke you like</Text>
            <Text style={HomeStyles().text}>3) Enjoy the image generated by AI illustrating the joke</Text>
      </View>
      <Pressable
        style= {HomeStyles().button}
        onPress={() =>
          navigation.navigate('JokesScreen')
        }
      >
        <Text style={HomeStyles().buttonText} >See the Jokes ⇒</Text>
      </Pressable>
    </View>
    )
  }