import { Text, View, TouchableOpacity } from 'react-native'
import { Link } from 'expo-next-react-navigation'

import { HomeStyles } from '../styles/HomeStyles' 

const HomeScreen = () => {

    return (
    <View style={HomeStyles().container}>
      <Text style={HomeStyles().welcome}>Welcome to random jokes generator!</Text>
      <Text style={HomeStyles().instructionTitle}>Simple usage instruction:</Text>
      <View style={HomeStyles().instructionContainer}>
            <Text style={HomeStyles().text}>1) Press the button to see a list of jokes</Text>
            <Text style={HomeStyles().text}>2) Press and hold the joke you like</Text>
            <Text style={HomeStyles().text}>3) Enjoy the image generated by AI illustrating the joke</Text>
      </View>
      <TouchableOpacity
        style= {HomeStyles().button}
        >
          <Link style={HomeStyles().buttonText} routeName='JokesScreen'>See the Jokes ⇒</Link>
      </TouchableOpacity>
    </View>
    )
  }

export default HomeScreen